import { chromium } from "playwright";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const page = await ctx.newPage();
const errs = [];
page.on("pageerror", (e) => errs.push("PAGEERR: " + e.message));
await page.goto("http://localhost:3000/galerie/mariages", { waitUntil: "load", timeout: 60000 }).catch((e)=>console.log("warn", e.message));
await page.waitForTimeout(7000);
await page.screenshot({ path: "docs/design-references/my-intro/gal-mariages-top.png" });
await page.screenshot({ path: "docs/design-references/my-intro/gal-mariages-full.png", fullPage: true });
console.log("errs:", errs.slice(0,6).join(" | ") || "none");
await browser.close();
process.exit(0);
